# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "207654bcf160a85ef5abf6fa59f8f832"
name = "ProCircle"
application_url = "https://procircle-server.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/app-uninstalled"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/api/webhooks/gdpr"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/api/webhooks/orders-paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_price_rules,write_price_rules,read_discounts,write_discounts,read_orders,read_products,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://procircle-server.onrender.com/auth/callback" ]


